# Generated by Django 6.0.5 on 2026-06-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_facebook_profile_github_profile_linkedin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
