# Generated by Django 6.0.5 on 2026-06-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("reader", "Reader"), ("writer", "Writer")],
                default="reader",
                max_length=20,
            ),
        ),
    ]
