# Generated by Django 6.0.5 on 2026-06-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="subject",
        ),
    ]
