# Generated by Django 6.0.5 on 2026-06-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_category_slug_alter_post_slug_alter_tag_slug"),
        ("blog", "0007_savedpost"),
    ]

    operations = []
